### ISSUE TITLE
rake aborted! undefined method `add_link' for #<Radiant::AdminUI::Tab:0x103881130>

### ISSUE THREAD

**Issue by atinypixel** [spanner/radiant-paperclipped_uploader-extension#1]
The issue is with your activate method. The add_link option for shards doesn't seem to exist.

```
** Invoke radiant:extensions:paperclipped_uploader:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
undefined method `add_link' for #<Radiant::AdminUI::Tab:0x10387eef8>
/Users/jones/dev/sandbox/radiant_development/vendor/extensions/paperclipped_uploader/paperclipped_uploader_extension.rb:21:in `activate'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/extension.rb:60:in `activate'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:105:in `to_proc'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/extension_loader.rb:98:in `each'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/extension_loader.rb:98:in `activate_extensions'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/initializer.rb:184:in `after_initialize'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/railties/lib/initializer.rb:179:in `process'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/railties/lib/initializer.rb:113:in `send'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/railties/lib/initializer.rb:113:in `run'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/lib/radiant/initializer.rb:148:in `run'
/Users/jones/dev/sandbox/radiant_development/config/environment.rb:12
/usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
/usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:521:in `new_constants_in'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/activesupport/lib/active_support/dependencies.rb:156:in `require'
/usr/local/lib/ruby/gems/1.8/gems/radiant-0.8.1/vendor/rails/railties/lib/tasks/misc.rake:4
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in `invoke_prerequisites'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `each'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/local/bin/rake:19:in `load'
/usr/local/bin/rake:19
```

**Comment by spanner** [comment]
ah, sorry. that's in the submenu extension. Forgot to mention it. I'll make it conditional in the morning.

will

**Comment by spanner** [comment]
should be ok now: submenu works but only if the extension is present.
